#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_dev
#spring.datasource.username=root
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=create-drop 
# create-drop: table is deleted when you stop the app (ideal for dev)

spring.datasource.url=jdbc:h2:mem:ecommerce_dev;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console